###
POST http://localhost:3500/garage/add
Content-Type: application/json

{
  "name": "Downtown Garage 2",
  "numFloors": 3,
  "spotsPerFloor": [10, 10, 10],
  "location": ["36.1583", "86.7761"],
  "overbookRate":  1.1,
  "isActive": true
}
